name: Auto Commit Trigger To Redeploy

on:
  schedule:
    - cron: "31 21 * * *"
    
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Make a dummy commit
        run: |
          echo "$(date)" > .autocommit_timestamp
          git add .autocommit_timestamp
          git commit -m "Auto deploy trigger [skip ci]" || echo "No changes to commit"
          git push
